### ISSUE TITLE
Reboots my Phone after showing the SIM Pin Panel

### ISSUE THREAD

**Issue by PrincessAkira** [Magisk-Modules-Alt-Repo/BuiltIn-BusyBox#1]
am i doing smth wrong here? XD

**Comment by zgfg** [comment]
You could try with v1.0.2 that checks does your phone supports /system/xbin and if not, mounts busybox to /system/bin

If not, then there must be something special with you (custom?) ROM, colliding with busybox

**Comment by PrincessAkira** [comment]
Well i used that.
Normal busybox works, but this just crashes my phone

**Comment by zgfg** [comment]
Can you find out to which system/* folder that other BB installs?

**Comment by PrincessAkira** [comment]
> Can you find out to which system/* folder that other BB installs?

system/bin

**Comment by PrincessAkira** [comment]
Just to be sure.
Should i use it with or without BusyBox NDK installed?

**Comment by zgfg** [comment]
You need only one BB module, not two installed and enabled in parallel

Closing the issue since you confirmed it's ok now. Thanks for the input
