### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Ai686Leo** [Magisk-Modules-Alt-Repo/BuiltIn-BusyBox#8]
After updating to the latest version 1.05 most applications (including system applications) crash on certain pages and are unresponsive
magisk is 26.1

**Comment by zgfg** [comment]
> After updating to the latest version 1.05 most applications (including system applications) crash on certain pages and are unresponsive magisk is 26.1

Sorry, I didn't receive e-mail notification for your report

Please see the same/similar Issue number 2

Please see my answers there - I have provided modified scripts and instructions how to test and to copy the log file

Please answer to my question (1) there

Then test with the script from (2) there and provide its log

If it still doesn't help, please test with the script from (3) there and provide the lof

**Comment by zgfg** [comment]
Please see
https://github.com/Magisk-Modules-Alt-Repo/BuiltIn-BusyBox/issues/7

Test the modified scripts provided there, and please provide answers (do  they help) and log files as described there

**Comment by Ai686Leo** [comment]
Sorry, I found that the questions of people who had problems with the same version as me have not been answered, I have not found where the script for testing is⊙⁠﹏⁠⊙

**Comment by Ai686Leo** [comment]
Sorry, I just saw that. Can you tell me in which directory the logs are generated?

**Comment by zgfg** [comment]
> Sorry, I just saw that. Can you tell me in which directory the logs are generated?

Hi
[BuiltIn-BusyBox_v1.0.5a-bugfix.zip](https://github.com/Magisk-Modules-Alt-Repo/BuiltIn-BusyBox/files/11679308/BuiltIn-BusyBox_v1.0.5a-bugfix.zip)

@Ai686Leo

I'd like to test the fix and release, please perform the following:

1) Download and install the attached BB v1.0.5a-bugfix module
and reboot

Based on results from the other users with similar issues, this version should hopefully work for you :-)

2) Upon rebooting, please use some root explorer like  MiXPlorer and go to:
/data/adb/modules/BuiltIn-BusyBox

find the file post-fs-data.log, copy to your Download folder, zip and provide me back here the log to see results

Please describe also does that v1.0.5.0-bugfix now works fine for you

Thanks

**Comment by zgfg** [comment]
Released:
https://github.com/Magisk-Modules-Alt-Repo/BuiltIn-BusyBox/releases/tag/106

**Comment by Ai686Leo** [comment]
Running well, thanks!
